src/main/java/jp/co/example/ecommerce_a/domain/Order.java
=> Order domainの誤字を修正しました。

src/main/resources/templates/item_list.html
2-4の追加機能、オートコンプリート機能を実装したので、確認をお願いいたします。
=> オートコンプリート機能の実装

pom.xml, src/main/java/jp/co/example/ecommerce_a/config/WebSecurityConfig.java, src/main/java/jp/co/example/ecommerce_a/config/package-info.java, src/main/java/jp/co/example/ecommerce_a/controller/LoginUserController.java, src/main/java/jp/co/example/ecommerce_a/controller/LogoutController.java, src/main/java/jp/co/example/ecommerce_a/controller/ShowItemListController.java, src/main/java/jp/co/example/ecommerce_a/domain/LoginUser.java, src/main/java/jp/co/example/ecommerce_a/form/LoginUserForm.java, src/main/java/jp/co/example/ecommerce_a/repository/UserRepository.java, src/main/java/jp/co/example/ecommerce_a/service/InsertUserService.java, src/main/java/jp/co/example/ecommerce_a/service/LoginUserService.java, src/main/java/jp/co/example/ecommerce_a/service/UserDetailServiceImpl.java, src/main/resources/templates/item_list.html, src/main/resources/templates/login.html
パスワードのハッシュ化／ログイン認証フィルターの実装を行いました。
誤字脱字、コメントなども見ていただけると嬉しいです！
=> パスワードのハッシュ化／ログイン認証フィルターの実装

src/main/java/jp/co/example/ecommerce_a/controller/ShopCartController.java, src/main/java/jp/co/example/ecommerce_a/controller/ShowItemListController.java, src/main/java/jp/co/example/ecommerce_a/domain/Order.java, src/main/java/jp/co/example/ecommerce_a/domain/OrderItem.java, src/main/java/jp/co/example/ecommerce_a/form/InsertCartForm.java, src/main/java/jp/co/example/ecommerce_a/repository/OrderItemRepository.java, src/main/java/jp/co/example/ecommerce_a/repository/OrderRepository.java, src/main/java/jp/co/example/ecommerce_a/repository/OrderToppingRepository.java, src/main/java/jp/co/example/ecommerce_a/service/ShopCartService.java, src/main/java/jp/co/example/ecommerce_a/service/shopCartService.java, src/main/resources/templates/cart_list.html, src/main/resources/templates/item_detail.html, src/main/resources/templates/item_list.html
ショッピングカートに商品を追加/表示/削除する機能を実装いたしました。
ご確認、よろしくお願い致します。
=> 1-5.ショッピングカートに商品を追加/表示/削除する(上級)

src/main/java/jp/co/example/ecommerce_a/config/WebSecurityConfig.java, src/main/java/jp/co/example/ecommerce_a/controller/InsertUserController.java, src/main/java/jp/co/example/ecommerce_a/controller/LoginUserController.java, src/main/java/jp/co/example/ecommerce_a/controller/ShopCartController.java, src/main/java/jp/co/example/ecommerce_a/controller/ShowItemDetailController.java, src/main/resources/templates/cart_list.html, src/main/resources/templates/item_detail.html, src/main/resources/templates/item_list.html, src/main/resources/templates/register_admin.html
=> バグ改修　パスを通した

src/main/java/jp/co/example/ecommerce_a/controller/InsertUserController.java, src/main/resources/templates/cart_list.html, src/main/resources/templates/item_detail.html, src/main/resources/templates/item_list.html
バグ改修をパスを通しました。
ご確認のほど、よろしくお願い致します。
=> バグ改修 パスを通しました。

src/main/java/jp/co/example/ecommerce_a/config/WebSecurityConfig.java, src/main/resources/templates/item_list.html
=> パスの修正と画像パスをリンク式に変更

src/main/resources/templates/item_list.html
=> 検索機能のパスを修正。

src/main/java/jp/co/example/ecommerce_a/config/WebSecurityConfig.java
未ログイン時でも商品詳細画面を閲覧できるように修正しました。
確認お願いします
=> 未ログイン時でも商品詳細画面を閲覧できるように修正しました。

src/main/resources/templates/item_list.html
=> 商品一覧の商品金額に「,」をつけました。

src/main/resources/templates/item_detail.html, src/main/resources/templates/item_list.html, src/main/resources/templates/order_confirm.html, src/main/resources/templates/order_finished.html
問い合わせフォームへ、各画面のヘッダーから飛べるように修正。
=> 問い合わせフォームへ、各画面のヘッダーから飛べるように修正。

src/main/java/jp/co/example/ecommerce_a/config/WebSecurityConfig.java, src/main/resources/templates/item_detail.html
商品詳細からカートリストに遷移を行えるようにした。
確認、お願い致します。
=> 商品詳細からカートリストに遷移を行えるようにした。

src/main/java/jp/co/example/ecommerce_a/controller/OrderConfirmController.java, src/main/resources/templates/order_confirm.html
=> 注文確認画面の表示がされるように実装を行いました。

src/main/resources/templates/error/4xx.html
=> 4xxエラーページのリンク修正

src/main/java/jp/co/example/ecommerce_a/config/WebSecurityConfig.java, src/main/java/jp/co/example/ecommerce_a/controller/ShopCartController.java, src/main/java/jp/co/example/ecommerce_a/service/ShopCartService.java
=> ショップカートのバグを修正。

src/main/java/jp/co/example/ecommerce_a/service/ShopCartService.java
=> ショップカートサービスのバグを解消しました。

src/main/java/jp/co/example/ecommerce_a/service/ShopCartService.java
=> ショップカートサービスのバグを改修。

src/main/java/jp/co/example/ecommerce_a/config/WebSecurityConfig.java, src/main/resources/templates/contactForm.html, src/main/resources/templates/contact_finish.html
=> お問合せ確認画面完了

src/main/resources/templates/cart_list.html, src/main/resources/templates/order_confirm.html
=> 金額0一個多い問題修正

src/main/java/jp/co/example/ecommerce_a/service/ShopCartService.java, src/main/resources/templates/item_detail.html
=> 商品詳細の見た目を整えた。

src/main/resources/templates/cart_list.html, src/main/resources/templates/item_detail.html, src/main/resources/templates/item_list.html, src/main/resources/templates/login.html, src/main/resources/templates/order_confirm.html, src/main/resources/templates/order_finished.html, src/main/resources/templates/top.html
=> 各HTMLお問合せに変遷追加＋郵便取得追加

src/main/java/jp/co/example/ecommerce_a/controller/InsertContactController.java, src/main/resources/templates/contactForm.html
=> コンタクトフォームを改修

src/main/java/jp/co/example/ecommerce_a/service/ShopCartService.java, src/main/resources/templates/contactForm.html
=> お問合せボタン改修Feature/button

src/main/java/jp/co/example/ecommerce_a/service/ShopCartService.java, src/main/resources/templates/item_detail.html
=> 商品リストの修正を行なった。

src/main/java/jp/co/example/ecommerce_a/form/InsertUserForm.java, src/main/resources/templates/register_admin.html
=> ユーザー登録input 内改修
